In [2]:
a = 'Apple'
# After variable name dot lga ke tab press krne pr inbuilt functions appear ho jate h....

a.endswith('q')

False

In [1]:
a = {'Car1':'Audi', 'Car2':'Mercedes', 'Car3':'BmW'}
a

{'Car1': 'Audi', 'Car2': 'Mercedes', 'Car3': 'BmW'}

In [2]:
type(a)

dict

In [3]:
a.keys

<function dict.keys>

In [4]:
print(a.keys)

<built-in method keys of dict object at 0x0000023A164CF480>


In [9]:
for x in a.values():
    print(x)

Audi
Mercedes
BmW


In [10]:
for x in a.keys():
    print(x)

Car1
Car2
Car3


In [11]:
for x in a.items():
    print(x)

('Car1', 'Audi')
('Car2', 'Mercedes')
('Car3', 'BmW')


In [12]:
import numpy as np


In [20]:
b = np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
a1 = np.zeros((3,3), dtype = int)
a1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
a1[1][1] = 7

In [35]:
a1

array([[0, 0, 0],
       [0, 7, 0],
       [0, 0, 0]])

In [37]:
q = np.random.rand(2,2)
q

array([[0.51442342, 0.12314264],
       [0.00196228, 0.96191482]])

In [43]:
np.random.randn(2,2)

array([[ 0.70899078,  0.74364271],
       [ 1.91620783, -0.54118105]])

In [52]:
np.random.randint(1,10,100).reshape(2,5,2,5)

array([[[[8, 1, 1, 2, 2],
         [1, 8, 8, 9, 8]],

        [[6, 2, 8, 8, 9],
         [3, 2, 6, 1, 1]],

        [[3, 5, 6, 4, 2],
         [3, 5, 1, 7, 9]],

        [[8, 4, 8, 2, 5],
         [8, 9, 8, 1, 9]],

        [[1, 1, 4, 9, 5],
         [8, 3, 9, 8, 2]]],


       [[[5, 7, 4, 4, 9],
         [8, 4, 5, 4, 3]],

        [[9, 1, 8, 2, 4],
         [4, 9, 4, 1, 3]],

        [[3, 3, 5, 3, 1],
         [1, 4, 6, 4, 4]],

        [[3, 1, 4, 6, 7],
         [2, 3, 7, 9, 5]],

        [[3, 8, 9, 7, 3],
         [3, 4, 1, 1, 8]]]])