In [1]:
import numpy as np
import pandas as pd

### What is Numpy?
#### NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. … A powerful N-dimensional array object. Sophisticated (broadcasting) functions.

In [16]:
### how to create 1D Array ?

a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


### ### how to create 2D Array ?

In [20]:

b = np.array([[1,2,3,4],[2,3,4,1]])
print(b)
print(type(b))

[[1 2 3 4]
 [2 3 4 1]]
<class 'numpy.ndarray'>


In [22]:
np.shape(a)

(4,)

In [23]:
np.shape(b)

(2, 4)

In [30]:
b.dtype

dtype('int32')

In [28]:
a.dtype

dtype('int32')

In [49]:
## zeroes
arr = np.zeros((3,3))
print(arr)
np.diag(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([0., 0., 0.])

In [51]:
arr2 = np.diag([1,2,3])
arr2

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
arr1 =np.ones((7,8))

In [43]:
print(type(arr),arr.dtype)

<class 'numpy.ndarray'> float64


In [61]:
random_nums = np.random.randint(12,100,4)
random_nums

array([37, 41, 80, 86])

In [64]:
np.random.randint()

array([0, 2])